CREATE TABLE EMPGASOLINERA (
idEmpGas CHAR(3),
nombreEmpGas VARCHAR2(30) NOT NULL UNIQUE,
pilaCEO VARCHAR2(20),
apeCEO VARCHAR2(20),
CONSTRAINT pk_idEmpGas PRIMARY KEY (idEmpGas)
);


CREATE TABLE SUCURSAL (
    idSucursalSub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idEmpGas CHAR(3) NOT NULL,
    noSucursal NUMBER(4) NOT NULL,
    direccion VARCHAR2(100) NOT NULL,
    telefono CHAR(10) NOT NULL,
    CONSTRAINT uq_idempnosuc UNIQUE (idEmpGas, noSucursal),
    CONSTRAINT fk_idempgas FOREIGN KEY (idEmpGas) REFERENCES EMPGASOLINERA(idEmpGas)
);


CREATE TABLE TIPOCOMBUSTIBLE (
    tipoComb VARCHAR2(7),
    precioCompra NUMBER(5,2) NOT NULL,
    precioVenta NUMBER(5,2) NOT NULL,
    CONSTRAINT ck_tipoComb CHECK (tipoComb IN ('Magna', 'Premium', 'Diesel')),
    CONSTRAINT ck_precio_magna CHECK (
        (tipoComb = 'Magna' AND precioCompra = 19.32 AND precioVenta = 23.45) OR
        (tipoComb = 'Premium' AND precioCompra = 20.39 AND precioVenta = 25.86) OR
        (tipoComb = 'Diesel' AND precioCompra = 22.69 AND precioVenta = 28.40)),
    CONSTRAINT pk_tipoComb PRIMARY KEY (tipoComb)
);


CREATE TABLE CISTERNA (
    idCisternaSub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idSucursalSub NUMBER NOT NULL,
    tipoComb VARCHAR2(7) NOT NULL,
    capacidadMax NUMBER(7,2) NOT NULL,
    litrosDisponibles NUMBER(7,2) NOT NULL,
    nivelBajo NUMBER(1),
    CONSTRAINT uq_idsuctipocomb UNIQUE (idSucursalSub, tipoComb),
    CONSTRAINT fk_sucursal FOREIGN KEY (idSucursalSub) REFERENCES SUCURSAL(idSucursalSub),
    CONSTRAINT fk_tipocomb FOREIGN KEY (tipoComb) REFERENCES TIPOCOMBUSTIBLE(tipoComb),
    CONSTRAINT nivelBajo_ck CHECK (nivelBajo IN (0,1)),
    CONSTRAINT capacidadMax_ck CHECK (
        (capacidadMax = 65000 AND tipoComb = 'Magna') OR
        (capacidadMax = 50000 AND tipoComb = 'Premium') OR
        (capacidadMax = 45000 AND tipoComb = 'Diesel')
    ),
    CONSTRAINT tipoComb_ck CHECK (tipoComb IN ('Magna', 'Premium', 'Diesel'))
);


-- Creación de la tabla BOMBA_SURTIDORA
CREATE TABLE BOMBA_SURTIDORA (
idBomba NUMBER(6),
estado VARCHAR2(20) NOT NULL,
CONSTRAINT pk_idBomb PRIMARY KEY(idBomba),
CONSTRAINT ck_estado CHECK (estado IN ('Activa', 'En_Mantenimiento', 'En_Falla'))
);


CREATE TABLE CIS_BOMB (
    idCisBombSub NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idBomba NUMBER(6) NOT NULL,
    idCisternaSub NUMBER NOT NULL,
    litrosTransferidos NUMBER(5,2) NOT NULL,
    fechaLlenado DATE,
    CONSTRAINT uq_bomba_cisterna UNIQUE (idBomba, idCisternaSub),
    CONSTRAINT fk_bomba FOREIGN KEY (idBomba) REFERENCES BOMBA_SURTIDORA(idBomba),
    CONSTRAINT fk_cisterna FOREIGN KEY (idCisternaSub) REFERENCES CISTERNA(idCisternaSub)
);


-- Creación de la tabla FALLA
CREATE TABLE FALLA (
idBomba NUMBER(6),
fechaFalla DATE,
descFalla VARCHAR2(100) NOT NULL,
perdidas NUMBER(7,2) NOT NULL,
fechaReparacion DATE,
CONSTRAINT pk_idbombfechafail PRIMARY KEY (idBomba, fechaFalla),
CONSTRAINT fk_bombid FOREIGN KEY (idBomba) REFERENCES BOMBA_SURTIDORA(idBomba) ON DELETE CASCADE
);


-- Creación de la tabla DISTRIBUIDOR
CREATE TABLE DISTRIBUIDOR (
    idDist CHAR(10),
    nombreDist VARCHAR2(30) NOT NULL,
    ventaTotal NUMBER(7,2) NOT NULL,
    correoDist VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_idDist PRIMARY KEY (idDist)
);


-- Creación de la tabla DIST_TELEFONO
CREATE TABLE DIST_TELEFONO (
idDist CHAR(10),
telefono CHAR(10) UNIQUE,
CONSTRAINT pkk_idDist PRIMARY KEY (idDist, telefono),
CONSTRAINT fkborrado_idDist FOREIGN KEY (idDist) REFERENCES DISTRIBUIDOR(idDist) ON DELETE CASCADE
);


-- Creación de la tabla DIST_DESPACHO_CISTERNA
CREATE TABLE DIST_DESPACHO_CISTERNA (
    idDist CHAR(10),
    idCisternaSub NUMBER(10),
    fechaPed DATE NOT NULL,
    fechaEnt DATE,
    litrosEnviados NUMBER(7,2),
    monto NUMBER(10,2) NOT NULL,
    CONSTRAINT pk_despacho PRIMARY KEY (idDist, idCisternaSub, fechaPed),
    CONSTRAINT fk_dist FOREIGN KEY (idDist) REFERENCES DISTRIBUIDOR(idDist),
    CONSTRAINT fk_cisterna2 FOREIGN KEY (idCisternaSub) REFERENCES CISTERNA(idCisternaSub)
);


-- Creación de la tabla EMPLEADO
CREATE TABLE EMPLEADO (
idEmp NUMBER(6),
pilaEmp VARCHAR2(20) NOT NULL,
apPatEmp VARCHAR2(20) NOT NULL,
apMatEmp VARCHAR2(20),
correo VARCHAR2(100) NOT NULL UNIQUE,
telefono CHAR(10) NOT NULL,
RFC CHAR(13) NOT NULL,
fechaContratacion DATE NOT NULL,
litrosVend NUMBER(6,2) DEFAULT 0,
idSup NUMBER(6) NULL,
CONSTRAINT pk_idEmp PRIMARY KEY (idEmp),
CONSTRAINT fk_idsup FOREIGN KEY (idSup) REFERENCES EMPLEADO(idEmp)
);


-- Creación de la tabla EMP_SUC
CREATE TABLE EMP_SUC (
    idSucursalSub NUMBER,
    idEmp NUMBER(6),
    fechaCont DATE,
    CONSTRAINT pk_emp_suc PRIMARY KEY (idSucursalSub, idEmp, fechaCont),
    CONSTRAINT fk_emp FOREIGN KEY (idEmp) REFERENCES EMPLEADO(idEmp),
    CONSTRAINT fk_suc FOREIGN KEY (idSucursalSub) REFERENCES SUCURSAL(idSucursalSub)
);


-- Creación de la tabla EMP_ASIGN_BOM
CREATE TABLE EMP_ASIGN_BOM (
idBomba NUMBER(6),
idEmp NUMBER(6),
fechaAsign DATE NOT NULL,
CONSTRAINT pk_idbombidemp PRIMARY KEY (idBomba, idEmp),
FOREIGN KEY (idBomba) REFERENCES BOMBA_SURTIDORA(idBomba),
FOREIGN KEY (idEmp) REFERENCES EMPLEADO(idEmp) ON DELETE CASCADE
);


-- Creación de la tabla CLIENTE
CREATE TABLE CLIENTE (
idCte NUMBER(12),
pilaCte VARCHAR2(20) NOT NULL,
apPatCte VARCHAR2(20) NOT NULL,
apMatCte VARCHAR2(20),
correo VARCHAR2(100) NOT NULL,
telefono CHAR(10) NOT NULL,
litrosComprados NUMBER(5,2) NOT NULL,
montoTotalGastado NUMBER(7,2),
CONSTRAINT pk_idcte PRIMARY KEY (idCte)
);


-- Creación de la tabla CLIENTE_VIP
CREATE TABLE CLIENTE_VIP (
idCte NUMBER(12),
noCompras NUMBER(4) NOT NULL CHECK (noCompras >= 0),
litrosAcumulados NUMBER(5,2) NOT NULL,
litrosRegalados NUMBER(1),
CONSTRAINT pkK_idctevip PRIMARY KEY (idCte),
CONSTRAINT litrosComp_ck CHECK (litrosComprados >= 30),
CONSTRAINT litrosreg_ck CHECK (litrosRegalados=3 OR litrosRegalados=0),
CONSTRAINT fkborrado_idCte FOREIGN KEY (idCte) REFERENCES CLIENTE(idCte) ON DELETE CASCADE
);


CREATE TABLE CLIENTE_PLACA (
idCte NUMBER(12),
placaCte VARCHAR2(10) UNIQUE,
CONSTRAINT pRIMk_idcte PRIMARY KEY (idCte, placaCte),
CONSTRAINT fk_idctese FOREIGN KEY (idCte) REFERENCES CLIENTE(idCte) ON DELETE CASCADE
);


-- Creación de la tabla VENTA
DROP TABLE VENTA CASCADE CONSTRAINTS;

CREATE TABLE VENTA (
    idVenta     NUMBER(8),
    idCte       NUMBER(12),
    idEmp       NUMBER(6),
    idBomba     NUMBER(6),
    tipoComb    VARCHAR2(7),
    fecha       DATE NOT NULL,
    litros      NUMBER(6,2) NOT NULL,
    monto       NUMBER(7,2) NOT NULL,
    CONSTRAINT pk_idVenta PRIMARY KEY (idVenta),
    CONSTRAINT fk_cte FOREIGN KEY (idCte) REFERENCES CLIENTE(idCte),
    CONSTRAINT fk_empbomb FOREIGN KEY (idBomba, idEmp) REFERENCES EMP_ASIGN_BOM(idBomba, idEmp),
    CONSTRAINT fk_comb FOREIGN KEY (tipoComb) REFERENCES TIPOCOMBUSTIBLE(tipoComb),
    CONSTRAINT venta_ck CHECK (tipoComb IN ('Magna', 'Premium', 'Diesel'))
);


SELECT v.idVenta,
c.pilaCte || ' ' || c.apPatCte AS nombre_cliente,
e.pilaEmp || ' ' || e.apPatEmp AS nombre_empleado,
s.idEmpGas, s.noSucursal,
v.tipoComb, v.litros, v.monto, v.fecha
FROM VENTA v
JOIN CLIENTE c ON v.idCte = c.idCte
JOIN EMPLEADO e ON v.idEmp = e.idEmp
JOIN EMP_SUC es ON e.idEmp = es.idEmp
JOIN SUCURSAL s ON es.idSucursalSub = s.idSucursalSub;